<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
  <!ELEMENT root (process)*>
  <!ELEMENT process (script|group|option)*>
  <!ATTLIST process id CDATA #REQUIRED>
  <!ELEMENT option EMPTY>
  <!ATTLIST option value CDATA #REQUIRED>
  <!ATTLIST option id CDATA #REQUIRED>
  <!ELEMENT script (option|content)*>
  <!ATTLIST script id CDATA #REQUIRED>
  <!ELEMENT content (#PCDATA)>
  <!ATTLIST content xml:space CDATA "preserve">
  <!ELEMENT group (model|option)*>
  <!ATTLIST group id CDATA #REQUIRED>
  <!ELEMENT model (sqlStr|option|field)*>
  <!ATTLIST model id CDATA #REQUIRED>
  <!ELEMENT sqlStr (#PCDATA)>
  <!ATTLIST sqlStr xml:space CDATA "preserve">
  <!ELEMENT field EMPTY>
  <!ATTLIST field nameA CDATA "">
  <!ATTLIST field format CDATA "">
  <!ATTLIST field value CDATA "">
  <!ATTLIST field end CDATA #REQUIRED>
  <!ATTLIST field position CDATA #REQUIRED>
  <!ATTLIST field type CDATA "0">
  <!ATTLIST field name CDATA "">
  <!ATTLIST field nameT CDATA "">
  <!ENTITY ldrPath "file:/home/are/data/Documents/FERNBACH/FLEXCUBE/etl/ldr/">
]>

<!--
/*
 *
 *  Copyright (C) 2010 Prince Onyenike <onyenikeprince@yahoo.com>
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
-->
<root>
  <process id="init">
    <option id="destinationPath" value="/usr/backup/manticore-ETLTools/data"/>
    <option id="ldrPath" value="file:/usr/backup/manticore-ETLTools/etl/ldr/"/>
    <option id="compress" value="0"/>
    <option id="concat" value="1"/>
    <option id="connection" value="FxF FSETL"/>
    <script id="10_truncate">
      <option id="active" value="1"/>
      <option id="phase" value="init"/>
      <content xml:space="preserve">import com.manticore.etl.*;
import com.manticore.etl.database.*;
import java.sql.*;
import groovy.sql.Sql;


logger.info("truncate tables in FSETL");

def String qryStr="""
	select 'truncate table ' || table_name "cmd" from user_tables 
	where not ( lower(table_name) like 'htm%'
			or lower(table_name)='gl_account'
		)
""";
ETLConnectionMap.close("FxF FSETL");


def Sql sql1 = new Sql(ETLConnectionMap.getConnection("FxF FSETL"));
sql1.eachRow( qryStr ) {
		logger.finer("execute ${it.cmd}"); 
		ETLConnectionMap.executeUpdate("FxF FSETL", it.cmd);
}
ETLConnectionMap.release("FxF FSETL", sql1.getConnection());</content>
      <option id="language" value="groovy"/>
    </script>
    <option id="dependancies" value=""/>
    <script id="01_prepare_attributes">
      <content xml:space="preserve">import com.manticore.util.ThreadList;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import groovy.sql.Sql;
import com.manticore.etl.*;
import com.manticore.etl.database.*;

//@todo: execute in parallel!

Logger logger=Logger.getLogger("");
logger.info("extract General Attributes from FSETL");

//def String[] fieldnames=["motive_nm", "organisation_unit_nm", "dealer_nm", "bank_segment_nm", "cost_center_nm", "ext_key_ctry_addr", "addr_type_nm", "ext_key_bbranch", "legal_form_nm", "federal_state_nm"]
def String now="to_date('20111231 00:00:00','YYYYMMDD hh24:mi:ss')" 
def me=0
def company=0
def value=0
def objects=[[
				"motive_nm"
				, "Delete MOTIVE_H;"
				, { -&gt; "INSERT INTO MOTIVE_H ( MOTIVE,ACTIVE,PCTR_D,MOTIVE_H_IP,MOTIVE_H_DC,IPROFITCENTER,MOTIVE_BASE,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A','${me}','${value}','${value}',NULL,NULL,$now,0,-1);" }
			], [
				"organisation_unit_nm"
				, "Delete ORGANISATION_UNIT_H;"
				, { -&gt; "INSERT INTO ORGANISATION_UNIT_H ( ORGANISATION_UNIT,ACTIVE,COMPANY,ADDRESS,ORGANISATION_UNIT_H_IP,ORGANISATION_UNIT_H_DC,PCTR_D,ORG_UNIT_TYPE,ORG_UNIT_INT_USER_FLAG,ORG_UNIT_INT_DEPT_FLAG,ORG_UNIT_INT_BRANCH_FLAG,ORG_UNIT_INT_COST_CENTER_FLAG,ORG_UNIT_EXT_ADDRESS_FLAG,ORG_UNIT_EXT_AGENT_FLAG,ORG_UNIT_EXT_VIRTUAL_FLAG,ADDRESS_CONTACT_FLAG,CREATE_DATE,CREATE_USER,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A',${company},NULL,'${value}','${value}',NULL,NULL,'0','0','0','0','0','0','0','0',NULL,NULL,$now,0,-1);"}
			], [
				"dealer_nm"
				, "Delete DEALER;"
				, { -&gt; "INSERT INTO DEALER ( DEALER,ACTIVE,COMPANY,DEALER_SHN,DEALER_DC,FUSER,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A',${company},'${value}','${value}',NULL,$now,0,-1);"}
			], [
				"bank_segment_nm"
				, "Delete BANK_SEGMENT_H;"
				, { -&gt; "INSERT INTO BANK_SEGMENT_H ( BANK_SEGMENT,ACTIVE,COMPANY,BANK_SEGMENT_H_SHN,BANK_SEGMENT_H_DC,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A',${company},'${value}','${value}',$now,0,-1);"}
			], [
				"cost_center_nm"
				, "Delete COST_CENTER_H;"
				, { -&gt; "INSERT INTO COST_CENTER_H ( COST_CENTER,ACTIVE,COMPANY,COST_CENTER_H_IP,COST_CENTER_H_DC,COST_CENTER_TYPE,COST_CENTER_INT_USER_FLAG,COST_CENTER_INT_DEPT_FLAG,COST_CENTER_INT_BRANCH_FLAG,COST_CENTER_EXT_ADDRESS_FLAG,COST_CENTER_EXT_AGENT_FLAG,COST_CENTER_EXT_UNREAL_FLAG,ADDRESS_CONTACT_FLAG,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A',${company},'${value}','${value}',1,'0','0','0','0','0',NULL,NULL,$now,0,-1);"}
			], [
				"addr_type_nm"
				, "Delete ADDR_TYPE_H;"
				, { -&gt; "INSERT INTO ADDR_TYPE_H ( ADDR_TYPE,ACTIVE,COMPANY,ADDR_TYPE_H_IP,ADDR_TYPE_H_DC,ADDR_SECOND_FLAG,ADDR_BANK_FLAG,ADDR_CLIENT_FLAG,ADDR_BROKER_FLAG,ADDR_PAYMENT_FLAG,ADDR_DELIVERY_FLAG,ADDR_AGENT_FLAG,ADDR_PERSONELL_FLAG,ADDR_ACC_WITH_FLAG,ADDR_ACC_AND_FLAG,ADDR_ACC_OR_FLAG,ADDR_NOSTRO_FLAG,ADDR_CONTRAHENT_FLAG,ADDR_AUTHORIZE_FLAG,ADDR_DESTINATION_FLAG,P82_FLAG,ADDR_SECURITY_FLAG,ADDR_ADMIN_PROPERTY_FLAG,ADDR_CMPY_CLIENT_FLAG,ADDR_CLDOC_FLAG,ADDR_SECBANK_FLAG,ADDR_ENCRYPTION_FLAG,ADDR_ISSUER_FLAG,ADDR_CONNECTION_FLAG,ADDR_EMPLOYER_FLAG,UP_DATE,UP_NO,UP_USER) VALUES (  ${me},'A',${company},'${value}','${value}','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0',$now,0,-1);"}
			], [
				"ext_key_bbranch"
				, "Delete BUSINESS_BRANCH_H;"
				, { -&gt; "INSERT INTO BUSINESS_BRANCH_H ( BUSINESS_BRANCH,ACTIVE,BUSINESS_BRANCH_H_IP,BUSINESS_BRANCH_H_DC,UP_DATE,UP_NO,UP_USER) VALUES ( ${me},'A','${value}','${value}',$now,0,-1);"}
			]]
			

objects.each {
	def f=it[0]
	def p=it[1]
	def i=it[2]

	logger.info("extract values for field $f");
	def String qryStr="""select 'select distinct company, $f v from ' || table_name || ' where not $f is null' as cmd from user_tab_columns where lower(column_name) = '$f'"""
	def String qryStr2="";
	def Sql sql1 = new Sql(ETLConnectionMap.getConnection("FxF Union Bank FSETL"));
	sql1.eachRow( qryStr ) {
		qryStr2 += qryStr2.length()==0 ? it.cmd : "\nunion " + it.cmd;
	}
    
	def out1 = new File('/usr/backup/manticore-ETLTools/data/' + f + '.sql')
    me=0
    out1.append "$p\n"
	sql1.eachRow( qryStr2 ) {
		me++
	company=it.company;
	value=it.v;
		out1.append "$i\n"
	}
	out1.append "commit;\n"
}
println "ready!"

ETLConnectionMap.release("FxF Union Bank FSETL", sql1.getConnection());</content>
      <option id="active" value="0"/>
      <option id="language" value="groovy"/>
      <option id="phase" value="init"/>
    </script>
  </process>
  <process id="transfer">
    <option id="destinationPath" value="/usr/backup/manticore-ETLTools/data"/>
    <option id="ldrPath" value="file:/usr/backup/manticore-ETLTools/etl/ldr/"/>
    <option id="compress" value="0"/>
    <option id="concat" value="1"/>
    <option id="connection" value="FxF FSETL"/>
    <script id="90_push">
      <option id="active" value="0"/>
      <option id="phase" value="transfer"/>
      <content xml:space="preserve">com.manticore.etl.FlatFileLoader.push(ldrPath, "/usr/backup/manticore-ETLTools/data", 10, true, logger);
</content>      <option id="language" value="groovy"/>    </script>    <script id="91_push_csv">      <option id="active" value="0"/>      <option id="phase" value="transfer"/>      <content xml:space="preserve">import com.manticore.etl.*;
import com.manticore.etl.database.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import groovy.sql.Sql;

Logger.getLogger("").info("start import of CSV files...");

String driverClassName = "oracle.jdbc.driver.OracleDriver";
String connectionString = "jdbc:oracle:thin:@172.16.10.16:1521:dbfxf";
String userName = "fsetl";
String password = "fsetl";
String destinationPath = "/usr/backup/manticore-ETLTools/etl/csv/";

CSVImport export = new CSVImport("FxF Union Bank FSETL", destinationPath);
export.addEntry("INTRATES_InterestRates_DataCapture", "FSETL.interest_rates", "dd/MM/yyyy", "dd/MM/yyyy HH:mm:ss.SSS", 3, 1, false);
export.addEntry("PFIMP_ImpairmentPortfolio_DataCapture", "FSETL.IMPAIRMENT_PORTFOLIO", "dd/MM/yyyy", "dd/MM/yyyy HH:mm:ss.SSS", 3, 1, false);
export.addEntry("upfront_fees", "FSETL.upfront_fees", "yyyy-MM-dd", "yyyy-MM-dd HH:mm:ss.SSS", 1, 0, false);
export.addEntry("portfolio_assignment", "FSETL.portfolio_assignment", "yyyy-MM-dd", "yyyy-MM-dd HH:mm:ss.SSS", 3, 0, false);
export.run();

def Sql sql = new Sql(ETLConnectionMap.getConnection("FxF Union Bank FSETL"));
def String sqlStr="""
	update FSETL.INTEREST_RATES
	set VALID = to_date('${POSTINGDATE}', 'yyyymmdd')
"""
Logger.getLogger("").info("adjust yield curves to posting date ${POSTINGDATE}, ${sql.executeUpdate(sqlStr)} updated");

sqlStr="""
	INSERT INTO L4567502_UPF_CHA_AMO
	(
		 TRS_NR_NM ,
		 CHARGE_TYPE_NM,
		 SALES_TYPE_NM,
		 CHARGE_DURATION_FRM,
		 CHARGE_DATE_CHANGE,
		 CHARGE_AMOUNT
	)
	select
	t2.trs_nr_nm ,
	'AMORTCHARGER' ,
	'IAS-TK-IN' ,
	case
		when t1.DAT_VALUE &gt;=t2.capital_duration_frm and t1.DAT_VALUE &lt;=t2.capital_duration_to then t1.DAT_VALUE
		else t2.capital_duration_frm
	end	,
	t2.capital_duration_to ,
	t1.amt_txn
	from fsetl.UPFRONT_FEES t1
	inner join L4567502_REGULAR_FLOATING_LOAN t2 on t1.COD_ACCT_NO=t2.TRS_NR_NM
"""
Logger.getLogger("").info("insert upfront charges for L4567502_REGULAR_FLOATING_LOAN, ${sql.executeUpdate(sqlStr)} updated");


sqlStr="""
	INSERT INTO L4567503_UPF_CHA_AMO
	(
		 TRS_NR_NM ,
		 CHARGE_TYPE_NM,
		 SALES_TYPE_NM,
		 CHARGE_DURATION_FRM,
		 CHARGE_DATE_CHANGE,
		 CHARGE_AMOUNT
	)
	select
	t2.trs_nr_nm ,
	'AMORTCHARGER' ,
	'IAS-TK-IN' ,
	case
		when t1.DAT_VALUE &gt;=t2.capital_duration_frm and t1.DAT_VALUE &lt;=t2.capital_duration_to then t1.DAT_VALUE
		else t2.capital_duration_frm
	end	,
	t2.capital_duration_to ,
	t1.amt_txn
	from fsetl.UPFRONT_FEES t1
	inner join L4567503_REGULAR_STAFF_LOAN t2 on t1.COD_ACCT_NO=t2.TRS_NR_NM
"""
Logger.getLogger("").info("insert upfront charges for L4567503_REGULAR_STAFF_LOAN, ${sql.executeUpdate(sqlStr)} updated");

sqlStr="""
insert into A4569501_ASS_TO_IMP_POR
select
 t2.CURRENT_ACCOUNT_NUMBER
 , case
 when SECTOR='INFORMATION AND COMMUNICATION' then 1
when SECTOR='TRANSPORTATION AND STORAGE ' then 2
when SECTOR='OIL AND GAS' then 3
when SECTOR='AGRICULTURE, FORESTRY AND FISHING' then 4
when SECTOR='REAL ESTATE ACTIVITIES ' then 5
when SECTOR='FINANCE AND INSURANCE' then 6
when SECTOR='MANUFACTURING' then 7
when SECTOR='CONSTRUCTION' then 8
when SECTOR='GENERAL' then 9
when SECTOR='GOVERNMENT' then 10
when SECTOR='GENERAL COMMERCE' then 11
when SECTOR='HUMAN HEALTH AND SOCIAL WORK ACTIVITIES' then 12
when SECTOR='PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES' then 13
when SECTOR='EDUCATION' then 14
when SECTOR='PUBLIC UTILITIES' then 15
when SECTOR='WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT  AND REMEDIATION ACTIVITIES' then 16
when SECTOR='CAPITAL MARKET' then 17
when SECTOR='ACTIVITIES OF EXTRATERRITORIAL ORGANIZATIONS AND BODIES' then 18
when SECTOR='ARTS, ENTERTAINMENT AND RECREATION' then 19
end "portfolio_nm"
from 
fsetl.PORTFOLIO_ASSIGNMENT t1
inner join A4569501_CURRENT_ACCOUNT t2 on 'ch_acct_'
|| t1.ACCOUNT_NUMBER_TEXT=t2.CURRENT_ACCOUNT_NUMBER and not t1.FACILITY_TYPE='LN'	
"""
Logger.getLogger("").info("insert portfolio assignment for A4569501_CURRENT_ACCOUNT, ${sql.executeUpdate(sqlStr)} updated");

sqlStr="""
insert into L4567502_ASS_TO_POR_IMP
select
 t2.trs_nr_nm
 , case
 when SECTOR='INFORMATION AND COMMUNICATION' then 1
when SECTOR='TRANSPORTATION AND STORAGE ' then 2
when SECTOR='OIL AND GAS' then 3
when SECTOR='AGRICULTURE, FORESTRY AND FISHING' then 4
when SECTOR='REAL ESTATE ACTIVITIES ' then 5
when SECTOR='FINANCE AND INSURANCE' then 6
when SECTOR='MANUFACTURING' then 7
when SECTOR='CONSTRUCTION' then 8
when SECTOR='GENERAL' then 9
when SECTOR='GOVERNMENT' then 10
when SECTOR='GENERAL COMMERCE' then 11
when SECTOR='HUMAN HEALTH AND SOCIAL WORK ACTIVITIES' then 12
when SECTOR='PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES' then 13
when SECTOR='EDUCATION' then 14
when SECTOR='PUBLIC UTILITIES' then 15
when SECTOR='WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT  AND REMEDIATION ACTIVITIES' then 16
when SECTOR='CAPITAL MARKET' then 17
when SECTOR='ACTIVITIES OF EXTRATERRITORIAL ORGANIZATIONS AND BODIES' then 18
when SECTOR='ARTS, ENTERTAINMENT AND RECREATION' then 19
end "portfolio_nm"
from 
fsetl.PORTFOLIO_ASSIGNMENT t1
inner join L4567502_REGULAR_FLOATING_LOAN t2 on t1.ACCOUNT_NUMBER_TEXT=t2.TRS_NR_NM and t1.FACILITY_TYPE='LN'	
"""
Logger.getLogger("").info("insert portfolio assignment for L4567502_REGULAR_FLOATING_LOAN, ${sql.executeUpdate(sqlStr)} updated");

sqlStr="""
insert into L4567503_ASS_TO_POR_IMP
select
 t2.trs_nr_nm
 , case
 when SECTOR='INFORMATION AND COMMUNICATION' then 1
when SECTOR='TRANSPORTATION AND STORAGE ' then 2
when SECTOR='OIL AND GAS' then 3
when SECTOR='AGRICULTURE, FORESTRY AND FISHING' then 4
when SECTOR='REAL ESTATE ACTIVITIES ' then 5
when SECTOR='FINANCE AND INSURANCE' then 6
when SECTOR='MANUFACTURING' then 7
when SECTOR='CONSTRUCTION' then 8
when SECTOR='GENERAL' then 9
when SECTOR='GOVERNMENT' then 10
when SECTOR='GENERAL COMMERCE' then 11
when SECTOR='HUMAN HEALTH AND SOCIAL WORK ACTIVITIES' then 12
when SECTOR='PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES' then 13
when SECTOR='EDUCATION' then 14
when SECTOR='PUBLIC UTILITIES' then 15
when SECTOR='WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT  AND REMEDIATION ACTIVITIES' then 16
when SECTOR='CAPITAL MARKET' then 17
when SECTOR='ACTIVITIES OF EXTRATERRITORIAL ORGANIZATIONS AND BODIES' then 18
when SECTOR='ARTS, ENTERTAINMENT AND RECREATION' then 19
end "portfolio_nm"
from 
fsetl.PORTFOLIO_ASSIGNMENT t1
inner join L4567503_REGULAR_STAFF_LOAN t2 on t1.ACCOUNT_NUMBER_TEXT=t2.TRS_NR_NM and t1.FACILITY_TYPE='LN'	
"""
Logger.getLogger("").info("insert portfolio assignment for L4567503_REGULAR_STAFF_LOAN, ${sql.executeUpdate(sqlStr)} updated");
		
ETLConnectionMap.release("FxF Union Bank FSETL", sql.getConnection())		
      </content>
      <option id="language" value="groovy"/>
    </script>
    <option id="dependancies" value="ln_retail ln_corporate flexcube_securities"/>
  </process>
  <process id="process">
    <option id="destinationPath" value="/usr/backup/manticore-ETLTools/data"/>
    <option id="ldrPath" value="file:/usr/backup/manticore-ETLTools/etl/ldr/"/>
    <option id="compress" value="0"/>
    <option id="concat" value="1"/>
    <option id="connection" value="FxF FSETL"/>
    <script id="01_testFreeDiskSpace">
      <option id="active" value="0"/>
      <option id="phase" value="init"/>
      <content xml:space="preserve">/*
 *
 *  Copyright (C) 2010 Prince Onyenike  &lt;onyenikeprince@yahoo.com&gt; 
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 * Credits to: https://www.ngdc.noaa.gov/wiki/index.php?title=Regular_Expressions_in_Groovy
 * where the main part of this script was copied from
 *
 */


 dfkOutput = 'df -k --sync'.execute().text
 long kbAvail = 0
 regex =  '''(?ix)     # enable case-insensitive matches, extended patterns
		(\\d+)     # 1: The disk space we want
		\\s+       # some whitespace
		\\d+%      # a number followed by %
		\\s+       # some more whitespace
		(/oradata*)  # 2: partition name'''
 pattern = ~regex
 matcher = pattern.matcher(dfkOutput)
 for (i=0; i &lt; matcher.getCount(); i++) {
	kbAvail += matcher[i][1].toLong()
 }
 println "/oradata: ${kbAvail} kb available"
 if (kbAvail &lt; 12000000) {
	println "insufficient disk space, will exit"
	System.exit(1);
 }
 
 kbAvail = 0
 regex =  '''(?ix)     # enable case-insensitive matches, extended patterns
		(\\d+)     # 1: The disk space we want
		\\s+       # some whitespace
		\\d+%      # a number followed by %
		\\s+       # some more whitespace
		(/)        # 2: partition name'''
 pattern = ~regex
 matcher = pattern.matcher(dfkOutput)
 for (i=0; i &lt; matcher.getCount(); i++) {
	kbAvail += matcher[i][1].toLong()
 }
 println "/: ${kbAvail} kb available"
 if (kbAvail &lt; 12000000) {
	println "insufficient disk space, will exit"
	System.exit(1);
 }
			</content>
      <option id="language" value="groovy"/>
    </script>
    <script id="05_resetDB">
      <option id="active" value="1"/>
      <option id="phase" value="init"/>
      <content xml:space="preserve">/*
 *
 *  Copyright (C) 2010 Prince Onyenike  &lt;onyenikeprince@yahoo.com&gt; 
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

import org.joda.time.*
import org.joda.time.format.*
import java.io.*
import org.apache.commons.io.*;

if ( POSTINGDATE.compareTo(INITDATE) == 0 ) {
	println "reset db on PD1=${POSTINGDATE}"
	def String scriptContent= """
		 set pause off
		 set feed off
	
		 conn fsdms/manager@dbfxf
	
		 prompt delete IMP tables ...
		 exec db_pck_f0018298.reset_imp_tabs;
		 prompt ...done
		
		 ------ delete HST tables (only dw_company_ctrl &gt; 0)------
		 prompt
		 prompt delete HST tables ...
		 exec db_pck_f0018298.reset_hst_tabs(PAR_DROP_HST_TABS =&gt; 0, PAR_CREATE_HST_TABS =&gt; 0, PAR_TRUNCATE_HST_TABS =&gt; 0, PAR_DEL_DW_COMPANY_CTRL =&gt; 0, PAR_NODEL_MUPO =&gt; 1, PAR_DEL_MUPO =&gt; 0 );
		 prompt ...done
		
		 ------ delete target tables, AR-tables ------
		 prompt
		 prompt delete target tables, AR-tables, ...
		 exec db_pck_f0018298.RESET_OTHERS(par_booking_date =&gt; to_date('${POSTINGDATE}','yyyymmdd'));
		 prompt ...done
		 
		 exit
		 /
	"""
	
	def File file=File.createTempFile("fxf",".sql")
	FileUtils.writeStringToFile(file, scriptContent)
	
	command = ["sh", "-c", "sqlplus /nolog @".concat(file.getAbsolutePath())]
	def Process p=Runtime.getRuntime().exec((String[]) command.toArray())
	p.waitFor()

} else {
	println "skip reset of the database on ${POSTINGDATE}"
}          
				</content>
      <option id="language" value="groovy"/>
    </script>
    <script id="09_restartScheduler">
      <option id="active" value="0"/>
      <option id="phase" value="init"/>
      <content xml:space="preserve">/*
 *
 *  Copyright (C) 2010 Prince Onyenike  &lt;onyenikeprince@yahoo.com&gt; 
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

import org.joda.time.*
import org.joda.time.format.*
import java.io.*
import org.apache.commons.io.*;

def String scriptContent= """
	 conn sysjcs/manager@dbfxf
	 shutdown immediate
	 startup
	 exit
	 /
"""

file=File.createTempFile("fxf",".sql")
FileUtils.writeStringToFile(file, scriptContent)

command = ["sh", "-c", "rs /nolog @".concat(file.getAbsolutePath())]
Runtime.getRuntime().exec((String[]) command.toArray())
				</content>
      <option id="language" value="groovy"/>
    </script>
    <script id="96_startRedwoodJCS">
      <option id="active" value="1"/>
      <option id="phase" value="after"/>
      <content xml:space="preserve">/*
 *
 *  Copyright (C) 2010 Prince Onyenike  &lt;onyenikeprince@yahoo.com&gt; 
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

import org.joda.time.*
import org.joda.time.format.*
import java.io.*
import org.apache.commons.io.*;

import groovy.sql.Sql
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.concurrent.Semaphore;
import com.manticore.etl.*; 
import org.joda.time.*;
import org.joda.time.format.*;
import java.util.logging.Level;
import java.util.logging.Logger;

Logger.getLogger("").info("start FxF processing...");

def DateTimeFormatter dateTimeFormatter=DateTimeFormat.forPattern("dd.MM.yyyy");
def DateTimeFormatter dateTimeFormatter2=DateTimeFormat.forPattern("yyyyMMdd");	
def String POSTINGDATE2=dateTimeFormatter.print( dateTimeFormatter2.parseDateTime(POSTINGDATE));

def String scriptContent= """
	set pause off
	set feed off

	WHENEVER sqlerror EXIT 1
	WHENEVER oserror EXIT 1

	 undefine CTRL_NO
	 column DW_CTRL new_value CTRL_NO noprint;
	 select db_pck_f0013005.fetch_next_dw_ctrl DW_CTRL from dual;

	 undefine ERR_FPRINTER
	 column E_FPRINTER new_value ERR_FPRINTER noprint;
	 select db_pck_f0012284.fsj_fprinter(NULL,'ERROR',NULL) E_FPRINTER from dual;

	 undefine HIST_FPRINTER
	 column H_FPRINTER new_value HIST_FPRINTER noprint;
	 select db_pck_f0012284.fsj_fprinter(NULL,'HISTORY',NULL) H_FPRINTER from dual;

	 -- default for prc_dw_ctrl is db_pck_f0013005.fetch_next_dw_ctrl
	 -- default for prc_error_fprinter   is db_pck_f0012284.fsj_fprinter(NULL,'ERROR',NULL)
	 -- default for prc_history_fprinter is db_pck_f0012284.fsj_fprinter(NULL,'HISTORY',NULL)
	 -- default for prc_print_history is 'N'


	 set pause off
	 set feed off
	 SET VERIFY OFF
	 SET SERVEROUTPUT ON SIZE 1000000
	 PROMPT Start of JOB_F0015000
	 DECLARE
		prc_dw_ctrl            NUMBER      := &amp;CTRL_NO;
		prc_error_fprinter     NUMBER(7,0) := &amp;ERR_FPRINTER;
		prc_history_fprinter   NUMBER(7,0) := &amp;HIST_FPRINTER;
		prc_print_history      VARCHAR2(1) := 'N';
		prc_job_id             NUMBER;

	 BEGIN
		jcs.clear_parameters('JOB_F0015000');
		jcs.parameter('JOB_F0015000', 'PAR_DW_CTRL',          prc_dw_ctrl);
		jcs.parameter('JOB_F0015000', 'PAR_ERROR_FPRINTER',   prc_error_fprinter);
		jcs.parameter('JOB_F0015000', 'PAR_HISTORY_FPRINTER', prc_history_fprinter);
		jcs.parameter('JOB_F0015000', 'PAR_PRINT_HISTORY',    prc_print_history);
		prc_job_id := jcs.submit('JOB_F0015000');
		commit;
		dbms_output.put_line('Script JOB_F0015000 submitted, job id='||prc_job_id);
	 END;
	 /
	 exit 0;
"""
command = ["sh", "-c", "rm -Rf ${destinationPath}${POSTINGDATE}"]
Runtime.getRuntime().exec((String[]) command.toArray()).waitFor()

["176","177","178","179","180","181","182","183"].each {
	command = ["sh", "-c", "rm -Rf ${destinationPath}*.${it}*"]
	Runtime.getRuntime().exec((String[]) command.toArray()).waitFor()
}

command = ["sh", "-c", "cp ${destinationPath}BLK_${POSTINGDATE}/* ${destinationPath}"]
Runtime.getRuntime().exec((String[]) command.toArray()).waitFor()

file=File.createTempFile("fxf",".sql")
FileUtils.writeStringToFile(file, scriptContent)

println("start processing from ".concat(file.getAbsolutePath()))

command = ["sh", "-c", "sqlplus 'OPS\$FSOPER/manager@dbfxf' @".concat(file.getAbsolutePath())]
Runtime.getRuntime().exec((String[]) command.toArray()).waitFor()
</content>      <option id="language" value="groovy"/>    </script>    <script id="95_startAnalytix">      <option id="active" value="1"/>      <option id="phase" value="transfer"/>      <content xml:space="preserve">/*
 *
 *  Copyright (C) 2010 Prince Onyenike  &lt;onyenikeprince@yahoo.com&gt; 
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

import org.joda.time.*
import org.joda.time.format.*
import java.io.*
import org.apache.commons.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

def String[] companies=['176', '177','178','179','180','181','182','183','184'];

for (String c: companies) {
	Logger.getLogger("").info("start Analytix for company id ${c}, this will run quite a while, please hang on...");
	def String scriptContent= """
		set pause off
		set feed off
		
		WHENEVER sqlerror EXIT 1
		WHENEVER oserror EXIT 1
		
		-- PROMPT start of script 10_start_Analytix_ETL.sql ...
		
		VARIABLE success NUMBER;
		DECLARE
			prc_posting_date    date := to_date('${POSTINGDATE}', 'yyyymmdd');
			prc_job_id          jcs_jobs.job_id%TYPE;
			prc_job_status      jcs_jobs.status%TYPE;
			prc_rw_script_name  varchar2(40)  := 'UE_RUN_ETL_PD';
		BEGIN
			jcs.clear_parameters(prc_rw_script_name);
			jcs.parameter(prc_rw_script_name, 'PAR_POSTING_DATE', prc_posting_date);
			jcs.parameter(prc_rw_script_name, 'PAR_COMPANY', '${c}');
			prc_job_id := jcs.submit(prc_rw_script_name);
			jcs.docommit;
			dbms_output.put_line('Script '||prc_rw_script_name||' submitted: job id='||prc_job_id);
		
			db_pck_f0018225.job_wait(prc_job_id);
			prc_job_status := jcs.status(prc_job_id);
			dbms_output.put_line('Script '||prc_rw_script_name||' finished: status= '||prc_job_status);
			IF  prc_job_status != 'READY' THEN
					:success := 1;
			ELSE 
					:success := 0;
			END IF;
		
		END; 
		/
		exit :success ;
	"""
	
	file=File.createTempFile("fxf",".sql")
	FileUtils.writeStringToFile(file, scriptContent)
	
	command = ["sh", "-c", "sqlplus 'OPS\$FSOPER/manager@dbfxf' @".concat(file.getAbsolutePath())]
	def int result=Runtime.getRuntime().exec((String[]) command.toArray()).waitFor()
	
	if (result!=0) {
		Logger.getLogger("").severe("processing of company ${c} failed. teminate the processing.")
		System.exit(1);
	} else
		Logger.getLogger("").severe("processing of company ${c} succeeded.")
}</content>